"""Update orders table with order_placed column

Revision ID: 5d5f82cd40ce
Revises: 64b05491debd
Create Date: 2024-12-16 01:39:21.544642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5f82cd40ce'
down_revision: Union[str, None] = '64b05491debd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('order_placed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_details', 'order_placed')
    # ### end Alembic commands ###
