"""Update orders table

Revision ID: 6bb8fcff0d5e
Revises: ff41c271d9c1
Create Date: 2024-12-15 23:00:33.453572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb8fcff0d5e'
down_revision: Union[str, None] = 'ff41c271d9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('order_side', sa.String(), nullable=False))
    op.add_column('order_details', sa.Column('order_type', sa.String(), nullable=False))
    op.alter_column('order_details', 'instrument',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_order_details_side', table_name='order_details')
    op.create_index(op.f('ix_order_details_order_side'), 'order_details', ['order_side'], unique=False)
    op.drop_column('order_details', 'side')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('side', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_order_details_order_side'), table_name='order_details')
    op.create_index('ix_order_details_side', 'order_details', ['side'], unique=False)
    op.alter_column('order_details', 'instrument',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('order_details', 'order_type')
    op.drop_column('order_details', 'order_side')
    # ### end Alembic commands ###
